/*
 Generated by typeshare 1.13.3
*/

export interface Review {
  /** The text content of the review. */
  content: string;
  /** The course ID this review is for. */
  courseId: string;
  /** Difficulty rating from 1-5. */
  difficulty: number;
  /** List of instructor names for this review. */
  instructors: string[];
  /** Number of likes (net of dislikes) this review has received. */
  likes: number;
  /** Overall rating from 1-5. */
  rating: number;
  /** Timestamp when the review was created or last updated. */
  timestamp: string;
  /** The user ID of the review author. */
  userId: string;
}

export interface GetReviewsPayload {
  /** List of reviews matching the query. */
  reviews: Review[];
  /** Number of unique users who have submitted reviews (if requested). */
  uniqueUserCount?: number;
}

export enum InteractionKind {
  /** Indicates that the user liked the review. */
  Like = 'like',
  /** Indicates that the user disliked the review. */
  Dislike = 'dislike',
}

export interface Interaction {
  /** Kind of interaction that occurred. */
  kind: InteractionKind;
  /** ID of the user associated with the interaction. */
  userId: string;
  /** ID of the course the interaction belongs to. */
  courseId: string;
  /** Referrer source from which the interaction was made. */
  referrer: string;
}

export interface GetUserInteractionForCoursePayload {
  /** Course ID the interactions belong to. */
  course_id: string;
  /** Referrer source the interactions were recorded from. */
  referrer: string;
  /** Interactions recorded for the course and referrer. */
  interactions: Interaction[];
}

export interface Instructor {
  name: string;
  nameNgrams?: string;
  term: string;
}

export interface Notification {
  review: Review;
  seen: boolean;
  userId: string;
}

export type ReqNode =
  | { type: 'course'; data: string }
  | {
      type: 'group';
      data: {
        operator: Operator;
        groups: ReqNode[];
      };
    };

export interface Requirements {
  prerequisitesText?: string;
  corequisitesText?: string;
  corequisites: string[];
  prerequisites: string[];
  restrictions?: string;
  logicalPrerequisites?: ReqNode;
  logicalCorequisites?: ReqNode;
}

export interface Subscription {
  courseId: string;
  userId: string;
}

export interface User {
  /** Microsoft Graph user identifier. */
  id: string;
  /** Primary email address associated with the user. */
  mail: string;
}

export interface UserResponse {
  /** Authenticated user information when available. */
  user?: User;
}

export enum Operator {
  And = 'AND',
  Or = 'OR',
}
