/*
 Generated by typeshare 1.11.0
*/

export interface Subscription {
  courseId: string;
  userId: string;
}

export interface User {
  id: string;
  mail: string;
}

export interface UserResponse {
  user?: User;
}
